[production]

jar_path = "memeBotTelegramBot.jar"

[production.stdout]
path = "bot.log"
mode = "w"

[production.stderr]
path = "bot.log"
mode = "w"

[testing]

jar_path = "app/build/libs/memeBotTelegramBot.jar"

[testing.stdout]
path = "out.log"
mode = "a"

[testing.stderr]
path = "err.log"
mode = "a"
