[production]

jar_path = "memeBotTelegramBot.jar"
correct_exit_codes = [0, 143]

[production.stdout]
path = "bot.log"
mode = "w"

[production.stderr]
path = "bot.log"
mode = "w"

[testing]

jar_path = "app/build/libs/memeBotTelegramBot.jar"
correct_exit_codes = [0, 251658240]

[testing.stdout]
path = "out.log"
mode = "a"

[testing.stderr]
path = "err.log"
mode = "a"
