/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package telegrambot;

import telegrambot.bot.BotInitializer;

public class App {
    public static void main(String[] args) {
        BotInitializer.initialize();
    }
}
